apiVersion: app/v1
kind: Replicaset
metadata:
  name: frontend
  label: 
    app: guestbook
    tire: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: fontend
  template:
    metadata:
      labels:
        tier: frontend
      spec:
        containers:
        - names: php-redis
          image: ger.io/google-sample/gb-front:v3